#!/bin/bash

set -e

if [[ "$TRAVIS_BRANCH" != "master" ]]; then
  echo "Skip the release process"
  exit 0
fi

tag="$(scripts/tag)"
dist_root_path="dists"
dist_path="${dist_root_path}/ansible-osx-package-${tag}.tar.bz2"

echo "Create release distribution ..."
mkdir -p $dist_root_path
tar cjf $dist_path $INSTALL_PREFIX

echo "Create GitHub Release ..."
ghr \
  --username aereal \
  --token $GITHUB_TOKEN \
  --prerelease \
  $tag \
  $dist_root_path
