#!/bin/bash

set -e

python_install_url='https://raw.githubusercontent.com/tagomoris/xbuild/master/python-install'

echo "python_install_url  = ${python_install_url}"

echo 'Update Homebrew ...'
brew update

echo 'Fetch python-install ...'
wget -O $PYTHON_INSTALL_PATH $python_install_url
chmod +x $PYTHON_INSTALL_PATH

echo 'Prepare Python directories ...'
sudo mkdir -p $PYTHON_PREFIX
sudo chown -R $(id -un):$(id -gn) $PYTHON_PREFIX
