#!/bin/bash

echo "Install ghr ..."
brew install tcnksm/ghr/ghr

echo "Install Python ..."
unset -e
${PYTHON_INSTALL_PATH} ${PYTHON_VERSION} ${PYTHON_PREFIX}
if [[ $? -ne 0 ]]; then
  cat /tmp/${USER}-python-install.log
  exit $?
fi
set -e

echo "Install Ansible ..."
${PYTHON_PREFIX}/bin/pip install --upgrade ansible
