#!/bin/bash

set -e

version="$(git tag | grep '^\d\+[.]\d\+[.]\d\+$' | sort -r | head -n 1)"
version="${version:-0.0.0}"
prerelease_version='nightly'
meta="$(date +'%Y%m%d%H%M%S')"
tag="${version}-${prerelease_version}+${meta}"

echo $tag
